### ISSUE TITLE
test create VDC cluster with kubernates template

### ISSUE THREAD

**Issue by ramezsaeed** [0-complexity/G8_testing#373]
**Description**
Test kubernetes template
https://github.com/openvcloud/kubernetes

**Blueprint Example**
```yml
services:
  - github.com/openvcloud/0-templates/sshkey/0.0.1__sshkey6:
      passphrase: '147258369'
  - github.com/openvcloud/0-templates/openvcloud/0.0.1__be-g8-3:
      address: 'be-g8-3.demo.greenitglobe.com'
      location: 'be-g8-3'
      token: '*********************************************************************'
  - github.com/openvcloud/0-templates/account/0.0.1__kubernetes:
      openvcloud: be-g8-3  
  - github.com/openvcloud/0-templates/vdc/0.0.1__kubernetesVDC12:
      account: kubernetes
      openvcloud: be-g8-3
  - github.com/openvcloud/kubernetes/setup/0.0.1__k8s:
      vdc: kubernetesVDC12
      sshKey: sshkey6
      workers: 1

actions:
  - template: github.com/openvcloud/0-templates/vdc/0.0.1
    actions: ['install']
  - template: github.com/openvcloud/kubernetes/setup/0.0.1
    actions: ['install']
```
